site_name: k8sgpt
site_url: https://k8sgpt.ai/docs
site_description: K8sGPT gives Kubernetes SRE superpowers to everyone
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/k8sgpt-ai/k8sgpt
edit_uri: https://github.com/k8sgpt-ai/docs/edit/main/docs/

nav:
  - Getting Started: 
      - Overview: index.md
      - Getting Started Guide: getting-started/getting-started.md
      - Installation: getting-started/installation.md
  - Tutorials: tutorials/index.md
  - Reference:
      - CLI: reference/cli/index.md
      - Contributing Guidelines: reference/contributing/guidelines.md
  - Explanation: explanation/index.md

theme:
  name: material
  anguage: "en"
  logo: imgs/logo-white.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link

plugins:
  - search
  - macros
